server:
    port: 80
spring:
    application:
        name: one-shoot-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: on
logging:
    pattern:
      level: "%5p [${spring.application.name:}] tenantId=%X{tenantId:-}"


    level:
        reactor.netty: DEBUG
        org.springframework.cloud.gateway: DEBUG
        org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
# okta:
#     oauth2:
#         issuer: https://dev-xxxxxx.okta.com/oauth2/default
#         client-id: xxxxxxxxxxxxxxxxxxxxxxx
#         client-secret: xxxxxxxxxxxxxxxxxxxxxxx
#         audience: api://default

management:
    endpoint:
        gateway:
            enabled: true
    endpoints:
        web:
            exposure:
                exclude: gateway